# Generated by Django 4.1.3 on 2022-11-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('psychology', 'Psychology'), ('philosophy', 'Philosophy'), ('psychoanalysis', 'Psychoanalysis')], default='philosophy', max_length=200),
        ),
    ]
