# Generated by Django 4.1.3 on 2022-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_title', models.CharField(max_length=250)),
                ('cap_body', models.TextField()),
            ],
        ),
    ]
