# Generated by Django 4.1.3 on 2022-11-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_post_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
