# Generated by Django 4.1.3 on 2022-12-01 09:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_capitulo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publish',)},
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='cap_body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
