# Generated by Django 4.1.3 on 2022-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_options_alter_capitulo_cap_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='cap_body',
            field=models.TextField(),
        ),
    ]
