# Generated by Django 4.1.3 on 2022-12-02 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_capitulo_cap_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitulo',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='sub_body1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='sub_body2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='sub_body3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='sub_title1',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capitulo',
            name='sub_title2',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capitulo',
            name='sub_title3',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='importantWords',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
