# Generated by Django 4.1.3 on 2022-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_image_capitulo_image1_capitulo_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
