# Generated by Django 4.1.3 on 2022-12-13 20:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_capitulo_cita1_capitulo_cita2_capitulo_cita3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
