# Generated by Django 4.1.7 on 2023-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_capitulo_cap_body_alter_capitulo_sub_body1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='sub_title1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='sub_title2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='sub_title3',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
